name: se7ety
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  shimmer_animation: ^2.2.2
  logger: ^2.0.2
  carousel_slider: ^5.1.1
  numeric_keyboard: ^1.1.0
  pinput: ^5.0.2
  device_preview: ^1.3.1
  go_router: ^16.2.2
  gap: ^3.0.1
  flutter_svg: ^2.2.1
  easy_localization: ^3.0.8
  image_picker: ^1.2.0
  smooth_page_indicator: ^1.2.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  lottie: ^3.3.2
  http: ^1.5.0
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
